{
  "formatVersion": "1.1",
  "component": {
    "group": "vvn.ai.smartekyc",
    "module": "smartekyc",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "smartekyc-1.0.0.aar",
          "url": "smartekyc-1.0.0.aar",
          "size": 863510,
          "sha512": "6935b88e9c73273da2a6b816e080c2a506d121f0ec6c84c4262b11d1bebbdd077f348e5599e3074ed757d6a58eb4c4c74289c6590e310c09da208b9f3ce5414f",
          "sha256": "5ef38d8ae91441cb6182621bd4c1c04cfa2bfffe8140a4a97abe1c24986f0e21",
          "sha1": "6d0b3eb7c41a30897c1ecf189834c752ab99bab3",
          "md5": "1a096ed936571e9502dca305eec4246a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-vision",
          "version": {
            "requires": "20.1.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0-RC4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-android",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "20030203.000550"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0-alpha05"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0-alpha05"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-alpha05"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "27.1-android"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-mlkit-face-detection",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-mlkit-barcode-scanning",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-mlkit-text-recognition",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "org.jmrtd",
          "module": "jmrtd",
          "version": {
            "requires": "0.7.18"
          }
        },
        {
          "group": "com.github.trungtai1805",
          "module": "qts-sdk",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.github.trungtai1805",
          "module": "htc-sdk",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "smartekyc-1.0.0.aar",
          "url": "smartekyc-1.0.0.aar",
          "size": 863510,
          "sha512": "6935b88e9c73273da2a6b816e080c2a506d121f0ec6c84c4262b11d1bebbdd077f348e5599e3074ed757d6a58eb4c4c74289c6590e310c09da208b9f3ce5414f",
          "sha256": "5ef38d8ae91441cb6182621bd4c1c04cfa2bfffe8140a4a97abe1c24986f0e21",
          "sha1": "6d0b3eb7c41a30897c1ecf189834c752ab99bab3",
          "md5": "1a096ed936571e9502dca305eec4246a"
        }
      ]
    }
  ]
}
